import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, ChevronDown, ChevronRight, Copy, Github, Menu, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import {
  auditEvents, controls, credibility, executionBoundaries, intentTypes, pipeline, principles,
  runtimeStates, users, x402Tracks,
} from './content';

const github = 'https://github.com/atonima-labs';
const reveal = { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .18 }, transition: { duration: .5 } };
const nav = [['Platform', '/#platform'], ['Architecture', '/#architecture'], ['Developers', '/#developers']];
const products = [
  { name: 'x402', href: '/x402', description: 'Agent-native payments and discovery' },
  { name: 'Runtime SDK', href: '/runtime', description: 'Deterministic execution lifecycle' },
  { name: 'Intent Infrastructure', href: '/intents', description: 'Validation, policy and compilation' },
];

export default function App() {
  const [menu, setMenu] = useState(false);
  const path = window.location.pathname.replace(/\/+$/, '') || '/';
  useEffect(() => { window.scrollTo(0, 0); }, [path]);
  return <div className="min-h-screen bg-ink text-white">
    <nav className="nav"><div className="shell flex h-[72px] items-center justify-between">
      <a href="/" className="flex items-center gap-3" aria-label="Atonima home"><Mark/><span className="font-semibold tracking-[-.02em]">atonima</span><span className="hidden rounded border border-white/10 px-2 py-1 font-mono text-[9px] uppercase tracking-[.15em] text-steel sm:inline">financial intent infrastructure</span></a>
      <div className="hidden items-center gap-7 lg:flex"><ProductMenu/>{nav.map(([label, href]) => <a key={label} className="nav-link" href={href}>{label}</a>)}</div>
      <div className="hidden items-center gap-3 lg:flex"><a href={github} target="_blank" rel="noreferrer" className="icon-button" aria-label="Atonima on GitHub"><Github className="size-4"/></a><a href="#contact" className="button button-small">Build with Atonima <ArrowRight className="size-3.5"/></a></div>
      <button className="icon-button lg:hidden" onClick={() => setMenu(v => !v)} aria-label="Toggle navigation" aria-expanded={menu}>{menu ? <X className="size-5"/> : <Menu className="size-5"/>}</button>
    </div><AnimatePresence>{menu && <motion.div initial={{height:0, opacity:0}} animate={{height:'auto', opacity:1}} exit={{height:0, opacity:0}} className="overflow-hidden border-t border-white/10 bg-ink lg:hidden"><div className="shell py-4"><p className="py-2 font-mono text-[9px] uppercase tracking-wider text-steel">Products</p>{products.map(p=><a key={p.name} href={p.href} className="block py-2 text-sm text-cloud" onClick={() => setMenu(false)}>{p.name}</a>)}<div className="my-2 h-px bg-white/10"/>{nav.map(([label, href]) => <a key={label} href={href} className="block py-2 text-sm text-cloud" onClick={() => setMenu(false)}>{label}</a>)}<a href="/#contact" className="button mt-4 w-full" onClick={() => setMenu(false)}>Build with Atonima</a></div></motion.div>}</AnimatePresence></nav>

    <main>{path === '/' ? <>
      <Hero/>
      <TrustStrip/>
      <Platform/>
      <Architecture/>
      <IntentDemo/>
      <X402/>
      <Principles/>
      <Audience/>
      <Vision/>
      <CTA/>
    </> : path === '/x402' ? <X402Page/> : path === '/runtime' ? <RuntimePage/> : path === '/intents' ? <IntentsPage/> : <NotFound/>}</main>
    <Footer/>
  </div>;
}

function ProductMenu(){return <div className="product-menu relative"><button className="nav-link flex items-center gap-1.5 py-6" aria-haspopup="true">Products <ChevronDown className="size-3"/></button><div className="product-popover">{products.map(p=><a key={p.name} href={p.href}><b>{p.name}</b><span>{p.description}</span></a>)}</div></div>}

function Mark({dark=false}:{dark?:boolean}) { return <span className={`mark ${dark ? 'mark-dark' : ''}`}><span/><i/></span>; }

function usePageMeta(title:string, description:string){useEffect(()=>{document.title=title;const selectors=['meta[name="description"]','meta[property="og:description"]','meta[name="twitter:description"]'];selectors.forEach(s=>document.querySelector(s)?.setAttribute('content',description));['meta[property="og:title"]','meta[name="twitter:title"]'].forEach(s=>document.querySelector(s)?.setAttribute('content',title));document.querySelector('link[rel="canonical"]')?.setAttribute('href',`${window.location.origin}${window.location.pathname}`);return()=>{document.title='Atonima | Financial Intent Infrastructure'}},[title,description])}

function ProductHero({tag,title,text,status}:{tag:string;title:string;text:string;status?:string}){return <section className="product-hero hero-grid pt-[72px]"><div className="shell py-24 sm:py-32"><a href="/" className="mb-10 inline-flex items-center gap-2 text-xs text-steel hover:text-white"><ArrowLeft className="size-3.5"/> Back to platform</a><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><span className="eyebrow">{tag}</span>{status&&<span className="mb-5 inline-flex rounded-full border border-signal/25 bg-signal/10 px-3 py-1 font-mono text-[9px] uppercase tracking-wider text-signal">{status}</span>}<h1 className="max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-cloud">{text}</p></motion.div></div></section>}

function X402Page(){usePageMeta('x402 | Atonima','A production-ready x402 facilitator and Bazaar discovery layer for agent-paid services on Stellar.');const specs=[
  ['Facilitator','Standard verify, settle and supported endpoints on testnet and pubnet, built on the Apache-2.0 @x402/stellar package.'],
  ['Strict authorization','Validate Soroban auth entries against the exact call, asset, amount and recipient; reject replay, expiry and tampering.'],
  ['Asset support','Support SEP-41 assets with USDC defaults, seven-decimal amount handling, classic keypairs and custom __check_auth accounts.'],
  ['Non-custodial fees','Sponsor network fees so buyers only need the payment asset. The facilitator never takes custody or becomes the source of funds.'],
  ['Self-hosting','Ship hosted and self-facilitated paths under a permissive OSI-approved license with configurable pricing, auth and rate limits.'],
  ['Wire conformance','Accept canonical v2 payloads unchanged, expose areFeesSponsored, return non-null rejection reasons and test both networks end to end.'],
];const discovery=[
  ['Catalog browsing','GET /discovery/resources with pagination and type, payTo, network, extensions, limit and offset filters.'],
  ['Natural-language search','GET /discovery/search with ranked retrieval, cursor pagination, partialResults and an evaluation plan for search quality.'],
  ['Automatic cataloging','Validate and index discovery metadata from PaymentPayload without requiring a separate seller registration step.'],
  ['HTTP + MCP resources','Treat MCP tools as first-class resources and key them using the resource URL and tool name tuple.'],
  ['Catalog integrity','Soft-drop invalid metadata, defend routeTemplate traversal after percent-decoding and report outcomes through EXTENSION-RESPONSES.'],
  ['Ecosystem compatibility','Track the evolving discovery conventions so Stellar resources remain interoperable with the wider x402 Bazaar ecosystem.'],
];return <><ProductHero tag="Product / x402" status="Product specification" title="Discover, authorize and pay for services—agent to agent." text="Atonima x402 brings payment facilitation and service discovery to agent commerce on Stellar, designed around the current x402 v2 wire format, Soroban authorization and open ecosystem conformance."/><SpecSection number="01" title="Facilitation without custody" intro="Settlement uses Stellar's authorization model: the buyer signs a narrowly scoped auth entry, the facilitator verifies it, builds the invocation, sponsors fees and submits it." items={specs}/><SpecSection dark number="02" title="Discovery makes services useful to agents" intro="The Bazaar turns isolated paid endpoints into a market agents can search. Resources remain interoperable with the broader x402 ecosystem and are indexed off-chain by default." items={discovery}/><X402Flow/><DeliverySection/><ProductCTA title="Build the open payment layer for Stellar agents."/></>}

function SpecSection({number,title,intro,items,dark=false}:{number:string;title:string;intro:string;items:string[][];dark?:boolean}){return <section className={`section ${dark?'bg-[#0b0e14]':'bg-paper text-ink'}`}><div className="shell"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><div><span className="eyebrow">{number} / Specification</span><h2 className={`section-title ${dark?'':'text-ink'}`}>{title}</h2><p className={`mt-5 leading-7 ${dark?'text-cloud':'text-slate-600'}`}>{intro}</p></div><div className={`grid gap-px overflow-hidden rounded-xl border ${dark?'border-white/10 bg-white/10':'border-slate-200 bg-slate-200'} sm:grid-cols-2`}>{items.map(([name,text])=><article key={name} className={`p-6 ${dark?'bg-ink':'bg-white'}`}><h3 className="font-semibold">{name}</h3><p className={`mt-3 text-sm leading-6 ${dark?'text-cloud':'text-slate-600'}`}>{text}</p></article>)}</div></div></div></section>}

function X402Flow(){return <section className="section bg-paper text-ink"><div className="shell"><SectionHead light eyebrow="03 / Agent interface" title="Discover → pay → retry, behind structured MCP tools." text="The agent-facing server provides deterministic inputs, outputs and machine-readable error codes so runtimes do not need pre-baked service integrations or prose parsing."/><div className="mt-12 grid gap-3 md:grid-cols-4">{[['01','SEARCH','Find ranked Stellar resources'],['02','SELECT','Inspect terms and metadata'],['03','AUTHORIZE','Sign exact or upto authority'],['04','CALL','Retry and receive the resource']].map(([n,k,t])=><div key={k} className="rounded-xl border border-slate-200 bg-white p-6"><span className="font-mono text-[9px] text-blue-700">{n}</span><h3 className="mt-8 font-mono text-xs font-semibold">{k}</h3><p className="mt-2 text-sm text-slate-600">{t}</p></div>)}</div></div></section>}

function DeliverySection(){const groups=[['Settlement schemes','exact plus a Stellar upto specification and implementation contributed upstream; batch settlement and auth-capture remain phase-two work.'],['Conformance evidence','Canonical-client e2e runs, both networks, settled hashes per network and scheme, supported contract output, and non-null rejection reasons.'],['Security readiness','Threat modeling and third-party review of settlement, auth validation, replay resistance, discovery poisoning and any introduced contract.'],['Developer adoption','Seller, buyer/agent and operator guides; SDK helpers; live testnet examples; and a path from documentation to discovery in under an hour.'],['Operations','Channel-account throughput strategy, monitoring, degraded-mode behavior, runbook, 99%+ public endpoint target and maintained spec regression coverage.'],['Open ecosystem','Permissive dependencies, self-hostable deployment, upstream coordination and a documented conformance-maintenance commitment.']];return <section className="section"><div className="shell"><SectionHead eyebrow="04 / Production standard" title="Reliability is proven at the wire—not asserted in copy." text="The product is ready when standard clients, independent reviewers and other operators can verify its behavior."/><div className="mt-12 divide-y divide-white/10 border-y border-white/10">{groups.map(([h,t],i)=><div key={h} className="grid gap-3 py-6 sm:grid-cols-[50px_220px_1fr]"><span className="font-mono text-[10px] text-steel">0{i+1}</span><h3 className="font-semibold">{h}</h3><p className="text-sm leading-6 text-cloud">{t}</p></div>)}</div></div></section>}

function RuntimePage(){usePageMeta('Runtime SDK | Atonima','The Atonima execution runtime for approved, compiled and attributed financial plans.');const lifecycle=[['Persist','Store approved plans with immutable links to policy, approval and attribution context.'],['Schedule','Support one-time and recurring evaluations without duplicate registrations.'],['Observe','Read balances, prices, liquidity, authorization and current ledger state.'],['Evaluate','Produce reproducible EXECUTE, SKIP or STOP decisions from explicit conditions.'],['Simulate','Check fees, balances, authorization, contract errors, outputs and slippage before submission.'],['Execute','Submit through the authorized financial adapter with idempotency and confirmation tracking.'],['Recover','Classify failures, retry transient errors and stop permanent or policy failures.'],['Close','Pause, resume, cancel, expire or complete plans with every transition audited.']];return <><ProductHero tag="Product / Runtime SDK" status="Architecture defined · SDK details pending" title="Operate approved financial plans reliably over time." text="The Atonima Runtime takes an approved, compiled and attributed execution plan and manages its live conditions, scheduling, simulation, submission and lifecycle—without expanding the authority it received."/><section className="section bg-paper text-ink"><div className="shell"><SectionHead light eyebrow="01 / Runtime responsibilities" title="Policy-bound execution, from evaluation to completion." text="This page reflects the current Atonima architecture. Public SDK methods, package names and compatibility claims will be updated from the Runtime SDK specification you provide."/><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{lifecycle.map(([h,t],i)=><article className="bg-white p-6" key={h}><span className="font-mono text-[9px] text-blue-700">0{i+1}</span><h3 className="mt-8 font-semibold">{h}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{t}</p></article>)}</div></div></section><SpecSection dark number="02" title="Deterministic at every boundary" intro="Identical state and compiled conditions must produce the same runtime decision. Dynamic calculation may use live data, but it remains inside approved constraints." items={[["Bounded calculation","Recompute amounts and direction while enforcing maximum value, retained balance, slippage and protocol rules."],["Skip semantics","Record evaluations and reasons without submitting transactions or consuming successful-execution limits."],["Idempotent execution","Prevent duplicate settlement across retries, scheduler runs and network uncertainty."],["Complete observability","Emit correlated preparation, simulation, submission, confirmation, failure and lifecycle events."]]}/><ProductCTA title="Integrate the runtime when the SDK contract is ready."/></>}

function IntentsPage(){usePageMeta('Intent Infrastructure | Atonima','Standardized financial intents, strict validation, policy decisions and deterministic compilation.');return <><ProductHero tag="Product / Intent Infrastructure" title="A standard boundary for financial intent." text="Atonima separates what an agent wants to accomplish from who may authorize it and how financial infrastructure should execute it."/><SpecSection number="01" title="Strict before powerful" intro="The validator selects an action schema, normalizes canonical values and fails closed on ambiguity before policy evaluation begins." items={[["Standard schemas","Transfer, swap, disbursement, contract call and treasury action formats with explicit required fields."],["Strict mode","Reject missing, malformed, unexpected and unsupported values by default."],["Sanitize mode","Optionally remove unknown non-sensitive fields while emitting an audit event."],["Canonical representation","Normalize identifiers, assets, amounts, timestamps and network values before hashing."]]}/><SpecSection dark number="02" title="Authority is a separate decision" intro="Validated structure does not imply permission. Policy binds organizational, financial, protocol and delegated authority before compilation." items={[["Policy evaluation","Allowed actions, assets, protocols, destinations, volumes, automation limits and delegation scope."],["Decision layer","Return ALLOW, DENY or REQUIRE_APPROVAL with matched rules, effective limits and reasons."],["Approval binding","Link approval to the exact intent hash and prevent material modification after authorization."],["Deterministic plans","Resolve approved intent into protocol-specific operations without inventing a new objective or widening authority."]]}/><ProductCTA title="Give agents an interface that finance can trust."/></>}

function ProductCTA({title}:{title:string}){return <section className="bg-signal text-ink"><div className="shell flex flex-col gap-6 py-14 lg:flex-row lg:items-center lg:justify-between"><h2 className="max-w-2xl text-3xl font-semibold tracking-tight">{title}</h2><div className="flex flex-col gap-3 sm:flex-row"><a href={github} target="_blank" rel="noreferrer" className="button button-dark"><Github className="size-4"/> GitHub</a><a href="/#contact" className="button button-light">Talk to Atonima <ArrowRight className="size-4"/></a></div></div></section>}

function NotFound(){usePageMeta('Page not found | Atonima','The requested Atonima page could not be found.');return <section className="hero-grid flex min-h-[calc(100vh-200px)] items-center pt-[72px]"><div className="shell py-24"><span className="font-mono text-sm text-signal">ERROR / 404</span><h1 className="mt-6 max-w-3xl text-5xl font-semibold tracking-[-.05em] sm:text-7xl">This route has no execution plan.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-cloud">The requested page does not exist or has moved. No action was taken.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/" className="button"><ArrowLeft className="size-4"/> Return home</a><a href="/x402" className="button button-ghost">Explore x402</a></div></div></section>}

function Hero() { return <section id="top" className="hero-grid relative overflow-hidden pt-[72px]">
  <div className="shell relative grid min-h-[780px] items-center gap-16 py-24 lg:grid-cols-[1.05fr_.95fr] lg:py-28">
    <motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.65}}>
      <div className="status-pill"><span className="pulse"/> Built Stellar-first · designed for financial AI</div>
      <h1 className="hero-title mt-7">The control layer between <span>AI intent</span> and financial execution.</h1>
      <p className="mt-7 max-w-xl text-lg leading-8 text-cloud">Atonima validates, authorizes, compiles, attributes and audits agent-generated financial actions before they reach wallets, payment systems or blockchain infrastructure.</p>
      <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#architecture" className="button">Explore the architecture <ArrowRight className="size-4"/></a><a href="/x402" className="button button-ghost">Explore x402</a></div>
      <p className="mt-6 flex items-center gap-2 text-xs text-steel"><Check className="size-3.5 text-signal"/> Agents express intent. Atonima controls execution authority.</p>
    </motion.div>
    <motion.div initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{duration:.7,delay:.12}} className="terminal-wrap">
      <div className="terminal-bar"><div className="flex gap-1.5"><i/><i/><i/></div><span>atonima / intent pipeline</span><span className="text-signal">● operational model</span></div>
      <div className="p-5 sm:p-7"><div className="code-label">INCOMING_INTENT</div><pre className="code-block">{`{\n  "action": "transfer",\n  "asset": "USDC",\n  "amount": "400",\n  "recipient": "GABC…7QX"\n}`}</pre>
      <div className="my-5 h-px bg-white/8"/>
      <div className="space-y-3">{[['01','SCHEMA','VALID'],['02','POLICY','REQUIRE_APPROVAL'],['03','AUTHORITY','PENDING']].map(([n,k,v],i)=><div className="terminal-row" key={k}><span>{n}</span><b>{k}</b><em className={i===0?'ok':'pending'}>{v}</em></div>)}</div>
      <div className="mt-6 rounded-lg border border-amber-400/20 bg-amber-400/[.06] p-4 font-mono text-[11px] leading-6 text-amber-200"><span className="text-amber-400">// EXECUTION PAUSED</span><br/>Amount exceeds autonomous threshold.<br/>No transaction has been constructed.</div></div>
    </motion.div>
  </div>
</section>; }

function TrustStrip(){return <div className="border-y border-white/8 bg-white/[.02]"><div className="shell grid sm:grid-cols-3">{credibility.map((item,i)=><div key={item.label} className={`flex items-center gap-3 py-5 ${i ? 'sm:border-l sm:border-white/8 sm:pl-8' : ''}`}><item.icon className="size-4 text-signal"/><div><span className="block text-[11px] text-steel">{item.label}</span><b className="text-sm font-medium">{item.value}</b></div></div>)}</div></div>}

function SectionHead({eyebrow,title,text,light=false}:{eyebrow:string,title:string,text?:string;light?:boolean}){return <motion.header {...reveal} className="max-w-3xl"><span className="eyebrow">{eyebrow}</span><h2 className={`section-title ${light?'text-ink':'text-white'}`}>{title}</h2>{text&&<p className={`mt-5 max-w-2xl text-base leading-7 ${light?'text-slate-600':'text-cloud'}`}>{text}</p>}</motion.header>}

function Platform(){return <section id="platform" className="section bg-paper text-ink"><div className="shell"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><SectionHead light eyebrow="01 / The platform" title="Infrastructure for controlled financial autonomy." text="Financial applications need more than agent identity. They need a reliable boundary where every proposed action can be checked before execution authority is granted."/><div className="grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 sm:grid-cols-2">{controls.map((c,i)=><motion.article {...reveal} transition={{delay:i*.06}} key={c.title} className="bg-white p-7"><div className="mb-8 grid size-10 place-items-center rounded-lg bg-ink text-signal"><c.icon className="size-5"/></div><h3 className="font-semibold">{c.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c.text}</p></motion.article>)}</div></div>
  <div className="mt-20 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-xl"><span className="eyebrow mb-2">Execution boundary</span><h3 className="text-xl font-semibold">Atonima coordinates execution across the financial stack.</h3><p className="mt-2 text-sm leading-6 text-slate-600">It can compile, simulate, sponsor, submit and monitor approved actions while connected networks and financial rails perform settlement.</p></div><div className="flex max-w-xl flex-wrap gap-2">{executionBoundaries.map(x=><span key={x} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs text-slate-500">{x}</span>)}</div></div></div>
  </div></section>}

function Architecture(){return <section id="architecture" className="section"><div className="shell"><SectionHead eyebrow="02 / Architecture" title="One enforceable path from request to outcome." text="Each layer answers one question, produces a structured output and leaves evidence for the next. Settlement remains with the underlying financial infrastructure."/>
  <div className="mt-14 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{pipeline.map((p,i)=><motion.article {...reveal} transition={{delay:i*.05}} key={p.name} className="module-card group"><div className="flex items-start justify-between"><span className="module-number">0{i+1}</span><p.icon className="size-5 text-steel transition group-hover:text-signal"/></div><h3 className="mt-10 text-xl font-semibold">{p.name}</h3><p className="mt-2 text-sm font-medium text-signal">{p.question}</p><p className="mt-4 text-sm leading-6 text-cloud">{p.detail}</p></motion.article>)}</div>
  <div className="mt-8 flex flex-wrap items-center gap-x-4 gap-y-2 rounded-xl border border-white/10 bg-white/[.03] p-4 font-mono text-[10px] text-steel"><b className="text-white">RUNTIME STATES</b>{runtimeStates.map((x,i)=><span key={x} className="flex items-center gap-4">{i>0&&<i className="size-1 rounded-full bg-white/20"/>}{x}</span>)}</div>
  </div></section>}

function IntentDemo(){const [copied,setCopied]=useState(false); const snippet=`const result = await atonima.intents.submit({\n  action: "swap",\n  assetIn: "USDC",\n  assetOut: "XLM",\n  amount: "100"\n});`;
return <section id="developers" className="section bg-paper text-ink"><div className="shell grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><motion.div {...reveal}><span className="eyebrow">03 / Developer model</span><h2 className="section-title text-ink">Describe the outcome.<br/>Bind the authority.</h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Agents submit a standardized financial intent—not raw transactions or arbitrary contract calls. Approved intents compile into deterministic plans with policy constraints attached.</p><div className="mt-8 flex flex-wrap gap-2">{intentTypes.map(x=><span key={x} className="rounded-md bg-slate-100 px-3 py-2 font-mono text-[10px] text-slate-600">{x}</span>)}</div></motion.div>
  <motion.div {...reveal} className="overflow-hidden rounded-2xl bg-[#0a0d13] shadow-2xl shadow-slate-900/15"><div className="flex items-center justify-between border-b border-white/10 px-5 py-3 font-mono text-[10px] text-steel"><span>intent.ts</span><button onClick={()=>{navigator.clipboard?.writeText(snippet);setCopied(true);setTimeout(()=>setCopied(false),1500)}} className="flex items-center gap-2 hover:text-white" aria-label="Copy code">{copied?<Check className="size-3"/>:<Copy className="size-3"/>}{copied?'Copied':'Copy'}</button></div><pre className="overflow-x-auto p-6 text-[12px] leading-7 text-[#c6d0df] sm:p-8"><code>{snippet}</code></pre><div className="border-t border-white/10 bg-white/[.03] px-6 py-4 font-mono text-[10px] text-signal">→ decision: REQUIRE_APPROVAL</div></motion.div>
  </div></section>}

function X402(){return <section id="x402" className="section x402-grid"><div className="shell"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><SectionHead eyebrow="04 / x402" title="Payments and discovery for agent commerce." text="Atonima extends its control model to x402 with non-custodial payment facilitation, service discovery and bounded agent spending on Stellar."/><motion.div {...reveal} className="lg:text-right"><span className="inline-flex rounded-full border border-signal/30 bg-signal/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-wider text-signal">x402 on Stellar</span><p className="mt-3 text-xs leading-5 text-steel">Open infrastructure for services that agents<br className="hidden lg:block"/> can discover, authorize and pay for.</p></motion.div></div>
  <div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{x402Tracks.map((x,i)=><motion.article {...reveal} transition={{delay:i*.05}} key={x.title} className="x402-card"><div className="flex items-center justify-between"><span className="font-mono text-xs text-steel">TRACK / {x.id}</span><x.icon className="size-5 text-signal"/></div><h3 className="mt-9 text-xl font-semibold">{x.title}</h3><p className="mt-3 min-h-[72px] text-sm leading-6 text-cloud">{x.text}</p><div className="mt-7 flex flex-wrap gap-2">{x.tags.map(t=><span key={t}>{t}</span>)}</div></motion.article>)}</div>
  </div></section>}

function Principles(){return <section className="section border-y border-white/8"><div className="shell"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><SectionHead eyebrow="05 / Delivery principles" title="Credibility lives in the details." text="Financial infrastructure earns trust through precise boundaries, verifiable behavior and an operating model others can inspect."/><div className="divide-y divide-white/10">{principles.map((p,i)=><motion.article {...reveal} transition={{delay:i*.05}} key={p.title} className="grid grid-cols-[auto_1fr] gap-5 py-6 first:pt-0"><div className="grid size-10 place-items-center rounded-lg border border-white/10"><p.icon className="size-4 text-signal"/></div><div><h3 className="font-semibold">{p.title}</h3><p className="mt-2 text-sm leading-6 text-cloud">{p.text}</p></div></motion.article>)}</div></div></div></section>}

function Audience(){return <section className="section bg-paper text-ink"><div className="shell"><SectionHead light eyebrow="06 / Built for the ecosystem" title="One control surface. Many financial workflows." text="Atonima is designed to sit behind the products teams already use and in front of the infrastructure that ultimately executes value."/><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{users.map((u,i)=><motion.article {...reveal} transition={{delay:i*.04}} key={u.title} className="bg-white p-7"><u.icon className="size-5 text-blue-700"/><h3 className="mt-8 font-semibold">{u.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{u.text}</p></motion.article>)}</div></div></section>}

function Vision(){return <section className="section"><div className="shell grid gap-12 lg:grid-cols-2 lg:gap-24"><SectionHead eyebrow="07 / Audit and observability" title="Every decision leaves a trail." text="Correlated events connect the original request to policy, approval, compilation and eventual settlement—so teams can reconstruct what happened and why."/><motion.div {...reveal} className="overflow-hidden rounded-xl border border-white/10 bg-black/20"><div className="flex justify-between border-b border-white/10 px-5 py-3 font-mono text-[10px] text-steel"><span>LIVE EVENT STREAM</span><span>correlation: int_4p8k</span></div><div className="divide-y divide-white/[.06]">{auditEvents.map(([time,event,detail,tone])=><div className="grid grid-cols-[76px_1fr] gap-3 px-5 py-3 font-mono text-[10px] sm:grid-cols-[80px_1fr_1.2fr]" key={event}><span className="text-steel">{time}</span><span className={tone==='good'?'text-signal':tone==='warn'?'text-amber-300':'text-white'}>{event}</span><span className="col-start-2 text-steel sm:col-start-auto">{detail}</span></div>)}</div></motion.div></div></section>}

function CTA(){return <section id="contact" className="bg-signal text-ink"><div className="shell grid gap-8 py-16 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="mb-3 block font-mono text-[10px] font-bold uppercase tracking-[.18em]">Build controlled financial autonomy</span><h2 className="max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">If your agents can move value, their authority should be explicit.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><a href={github} target="_blank" rel="noreferrer" className="button button-dark"><Github className="size-4"/> Explore the repository</a><a href="mailto:hello@atonima.com?subject=Build%20with%20Atonima" className="button button-light">Start a conversation <ArrowRight className="size-4"/></a></div></div></section>}

function Footer(){return <footer className="border-t border-white/8 bg-[#07090d]"><div className="shell py-12"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr]"><div><div className="flex items-center gap-3"><Mark/><b>atonima</b></div><p className="mt-4 max-w-sm text-sm leading-6 text-steel">Verification and control infrastructure for agent-generated financial actions.</p></div><div><b className="footer-head">Platform</b><div className="mt-4 space-y-3">{nav.slice(0,3).map(([l,h])=><a className="footer-link" href={h} key={l}>{l}</a>)}</div></div><div><b className="footer-head">Connect</b><div className="mt-4 space-y-3"><a className="footer-link" href={github} target="_blank" rel="noreferrer">GitHub <ChevronRight className="size-3"/></a><a className="footer-link" href="mailto:hello@atonima.com">Contact <ChevronRight className="size-3"/></a></div></div></div><div className="mt-12 flex flex-col gap-3 border-t border-white/8 pt-6 text-[11px] text-steel sm:flex-row sm:justify-between"><p>© 2026 Atonima Labs. All rights reserved.</p><p>Stellar-first · Infrastructure-agnostic by design</p></div></div></footer>}
